name: esm-2024
channels:
- conda-forge
dependencies:
- python>=3.11
- pip

  # main packages
- numpy
- scipy
- pandas>=2
- geopandas>=0.13.2
- xarray
- networkx
- yaml
- pyomo
- netcdf4
- pypsa>=0.27
- atlite>=0.2.12
- powerplantmatching>=0.5.12
- rasterio>=1.3.2
- pysheds

  # interactive python
- ipython
- jupyterlab

  # reading excel tables
- tabula-py
- xlrd
- lxml
- pytables
- pyxlsb
- openpyxl

  # geodata utilities
- shapely>2
- pyepsg
- cartopy>=0.22
- country_converter

  # plotting
- matplotlib>=3.6
- plotly
- hvplot
- holoviews
- geoviews>=1.10
- graphviz

  # publishing
- jupyter-book
- ghp-import

- pip:
  - highspy
