name: esm
channels:
- conda-forge
dependencies:
- python==3.9
- pip

  # main packages
- numpy
- scipy
- pandas
- geopandas
- xarray
- networkx
- yaml
- pyomo
- netcdf4
- pypsa>=0.20
- atlite>=0.2.9
- powerplantmatching>=0.5.4
- rasterio!=1.2.10

  # interactive python
- ipython
- jupyterlab

  # reading excel tables
- tabula-py
- xlrd
- lxml
- pytables
- pyxlsb
- openpyxl

  # geodata utilities
- fiona<=1.18.20
- shapely<2.0
- proj
- geopy
- pyepsg
- cartopy
- descartes

  # plotting
- matplotlib
- seaborn
- plotly
- hvplot
- holoviews
- geoviews
- graphviz

  # publishing
- jupyter-book
- ghp-import